### ISSUE TITLE
Looking forward to the official code.

### ISSUE THREAD

**Issue by KimManjin** [TimSong412/OmniTrackFast#1]
Hi,

congratulations for the impressive work!

I'm just wondering when the authors will release the official code.

Many thanks.

**Comment by TimSong412** [comment]
Hi Kim
Sorry for the late reply, the official code depends on the review of the following conference. We still want to improve it!

**Comment by turandai** [comment]
Looking forward too! Can't wait to try it. Wish you get an acceptance soon.

**Comment by turandai** [comment]
Hi, congrats on acceptance by ECCV'24, looking forward to the code! Can't wait to try it!
